### ISSUE TITLE
[Feature Request] Expand The Entension Window

### ISSUE THREAD

**Issue by Jack1789** [Ruud14/Page-Manipulator#1]
Hi, I have just tried your extension and found it very useful indeed, but would you please make bigger its window? Centered and maybe resizable as well, so it gets really comfortable to handle it.

Thanks.

**Comment by RandityaHundal** [comment]
k

**Comment by Ruud14** [comment]
Thanks for your feature request @Jack1789 
I Added realizability support together with some other features and bug fixes in the newest release. Check it out here:
https://github.com/Ruud14/Page-Manipulator/releases/tag/v0.3.1-alpha

The new version will be available in the chrome extension store as soon as it is approved.
