### ISSUE TITLE
How to back up Css html Js had been created ?

### ISSUE THREAD

**Issue by kaiter999** [Ruud14/Page-Manipulator#12]
I will Uninstall chorme and reinstall, How to back up and restore Css html Js had been created ?

**Comment by Ruud14** [comment]
If you have enabled synching chrome across your Google account, then all files with less than 8000 characters will be automatically saved across your account. [Here](https://support.google.com/chrome/answer/185277?hl=en-GB&co=GENIE.Platform%3DDesktop) is a guide on how to do so. 

For all other files (over 8000 characters) however, you unfortunately have to back up manually.
e.g. create separate CSS, HTML, and JS files on your device for every file in the extension.
