### ISSUE TITLE
saving

### ISSUE THREAD

**Issue by mojo111111** [Ruud14/Page-Manipulator#13]
is it possible to save current settings done on pc then copy it to new pc and same settings are applied like first pc?

ive tried diffrent methods but none seems to work

**Comment by Ruud14** [comment]
If I understand correctly, you want to save files together with their settings to another pc.

You can achieve this by synching your google account (in chrome). When you have synched chrome, all your extensions, including Page Manipulator, will be installed on both pc's and the files and settings in both extensions will be the same.

Hope this helps :)
