### ISSUE TITLE
Domain Wildcard

### ISSUE THREAD

**Issue by NXTOnline** [Ruud14/Page-Manipulator#17]
Hallo, wäre schön wenn man einen Wildcard setzen könnte wie zum beispiel
example.com/$ oder so etwas damit alle adressen einer Domain so mit inhalt gefüllt werden könnten.

Hello, would be nice if you could set a wildcard like for example
example.com/$ or something so that all addresses of a domain could be filled with content.

**Comment by Ruud14** [comment]
I am not sure if this is what you mean, but you can change the 'Matching pages' dropdown to 'Recursive'.
This will make sure that the manipulations will be applied on every sub-URL of a domain
![githubissue](https://user-images.githubusercontent.com/40769366/151530919-9b18611a-de6f-479f-a3b0-34eb2440ebf9.jpg)

**Comment by NXTOnline** [comment]
xD oh das komplett übersehen habe. Gut nun klappt es xD Danke für den hinweis.

xD oh that have completely overlooked. Well now it works xD Thanks for the hint.
