### ISSUE TITLE
Sometimes the extension is turned OFF 

### ISSUE THREAD

**Issue by islamghost1** [Ruud14/Page-Manipulator#20]
Sometimes the extension is turned OFF on a page refresh. Even if the link is added to the Active websites section .

**Comment by Ruud14** [comment]
Hi, thanks for reporting the issue.

I don't fully understand which of the following two things is happening.
1. On <ins>one</ins> website (of which the URL is in the active websites section) the extension stays ON on some refreshes and turns OFF on others.
2. On some websites the extension stays ON after refreshing and on other websites the extension turns OFF after refreshing. (where the URLs of both sites are in the active websites section.)

**Comment by islamghost1** [comment]
Hi, thanks for your reply. 

- Sorry, maybe I didn't describe the problem very well. So this bug happened on just one page where the extension was ON and on a page refresh, it turns OFF. So in response to your question, it's case number **2**.

-   Also I have another extension “**Tab auto refresh**”, its role is to refresh the web pages after specific time.(I just wanted you   to consider this parameter) . 

To resolve the problem, I had to reinstall your extension, and it works very well.

**Comment by Ruud14** [comment]
Okay, thanks for explaining. 
Happy to hear that the issue has been resolved. 
Right now I don't know what the issue could have been, but I will be looking into that.
I'll close this issue for now, feel free to reopen it if the issue occurs again.
