### ISSUE TITLE
Defer scripts

### ISSUE THREAD

**Issue by Akash-116** [Ruud14/Page-Manipulator#21]
Hello, 

Is it possible to add my custom script with defer enabled into the main document? I update some elements and add a custom button to all those elements, so it is necessary for me to defer my script; otherwise they are not being computed.

Or, its okay if the script is appended to the body of the document, rather than being placed in the head tag

**Comment by Ruud14** [comment]
Hi,

If I understand correctly, you want to delay your code from being executed.
The extension does not have a feature to delay injection, but you could always add a delay in your own code. 
You could add a setTimeout or add a listener for DOM load completion.

Appending the script to the body is also okay.

**Comment by Akash-116** [comment]
Actually, my issue was a bit different. The elements were taking some time to load. But the DOM load completion event was called even before these elements were loaded. And so, my javascript was running on empty elements.

Timeout would have worked, but I want the javascript to start working immediately after the elements are loaded from server.

Finally I ended up using a button where the user has to manually invoke the functionality (This actually ends up giving the user more freedom as to whether use the functionality or not; and so ended up as a ~feature~)

So, as a **SUMMARY**: 
I would like to suggest the **feature of adding the scripts to the end of the body tag**, like providing an option whether to add them to the start of head tag, or end of body; similar to what you have provided for HTML injection.

Or rather, give the option of injecting <script defer="">...</script> OR <script>...</script>  (Here, I think the first one would be equivalent to adding the code to the end of body tag)

**P.S.** : Thanks for your reply. Feel free to close this issue with a comment.

**Comment by Ruud14** [comment]
Okay, thanks for your feature request, and I'm happy to hear you got it working!
