### ISSUE TITLE
Javascript files does not load automatically

### ISSUE THREAD

**Issue by mp222sf** [Ruud14/Page-Manipulator#24]
Hi,

My JS files does not load automatically. (CSS does)
Everything was working fine until 5-6 days ago.

- I have entered the correct "Active Website"
- I have checked the "Active" checkbox
- I have tried with both Exact matching and Recursive matching
- And I have checked the "Auto" checkbox.

I saw you made som changes 4th nov ("Changed everything to work with manifest V3").
Could it have anything to do with that?

**Comment by Ruud14** [comment]
Hi,

Thanks for reporting the issue.
The issue defenitely has something to do with the new manifest v3 changes.
I had to rewrite the JS injection process to comply with the new manifest v3 rules.

I thoroughly tested the new JS injection of course, but unfortunately the new approach seems to not be perfect (yet).

Do all of your JS files not load automatically or is it a specific one?
If the latter is the case, what makes that JS injection different from the others?

Could you also check your browser console of the page that should have the JS injected (f12 -> console) and the console of the extension (open the extension, right click anywhere -> inspect element -> console) to see what (if any) errors are shown.

Also, do injections still work when manually injecting them?

Thanks a lot!

**Comment by mp222sf** [comment]
Hi Ruud,

1. All JS files does not load automatically.
2. I can see this error in the console:

Error handling response: TypeError: Cannot read properties of null (reading 'dispatchEvent')
    at injectUserCode (chrome-extension://mdhellggnoabbnnchkeniomkpghbekko/content.js:369:30)
    at manipulate (chrome-extension://mdhellggnoabbnnchkeniomkpghbekko/content.js:386:13)
    at load_data_from_storage_and_manipulate (chrome-extension://mdhellggnoabbnnchkeniomkpghbekko/content.js:99:21)
    at chrome-extension://mdhellggnoabbnnchkeniomkpghbekko/content.js:120:9

3. The injections still work when I press the "Manipulate" button.

**Comment by mp222sf** [comment]
Now I tried to deactivate all JS files except one, and that one works.
But when I activate two JS files with the same URL ("Active Website") it gives me the error in the previous post.

The first error in the console is:
"at injectUserCode (chrome-extension://mdhellggnoabbnnchkeniomkpghbekko/content.js:369:30)"

and it points me to this code:

`// Add the new JS to the page if it wasn't already on there.
            if(!alreadyInjected)
            {
                // Send event to event target.
                var event = new CustomEvent("manipulate", {'detail': {
                    code: request.code,
                    filename: request.filename
                }});
                event_target.dispatchEvent(event);
                added_js.push(request.filename);  
            }`

**Comment by Ruud14** [comment]
Okay, that is very helpfull, thanks a lot!

I will look into this and I'll try to fix it tomorrow.

I'll keep you updated.

**Comment by Ruud14** [comment]
I made [some changes](https://github.com/Ruud14/Page-Manipulator/pull/25/commits/8688444f548cef5c289a4f0a64b1ace760e80b1d) and the issue seems to be fixed now. 

This update goes live once the changes are approved by the chrome extension store, this usually takes a couple of days. 

If new issues arise please report them again as this is really helpful. 

Thanks again for reporting the issue!

**Comment by Ruud14** [comment]
The update (0.5.4) is live now.
Can you confirm that it is working again now?
