### ISSUE TITLE
Page Manipulator stopped automatically injecting code on page load load

### ISSUE THREAD

**Issue by jvgpinheiro** [Ruud14/Page-Manipulator#27]
Browser: Chrome version 107.0.5304.107

![image](https://user-images.githubusercontent.com/61484693/201339300-3187b172-a142-461a-ad51-b75c80a3c1f9.png)

**Comment by Ruud14** [comment]
Hi, thanks for reporting

Are you injecting multiple JS files into one webpage? 
If so, this is the same issue as #24 .
I fixed that issue this morning, right now I am waiting for approval from the chrome extension store to publish the new version.

If you are not injecting multiple JS files into one webpage, please explain what is being injected into the page.

**Comment by jvgpinheiro** [comment]
Yes, I'm injecting multiple files into the page. Great, I'll wait for the new version.

Btw, I love the extension. It's such a time saver in my work environment.
