### ISSUE TITLE
How to replace code with new code?

### ISSUE THREAD

**Issue by rajatsrkr** [Ruud14/Page-Manipulator#31]
How would I replace code instead of creating more? For example, I can change what a site says on inspect element, but it doesn't save. How would I write code to permanently change what a website says every time I load the page?

**Comment by Ruud14** [comment]
Hi,

You could inject javascript that finds the element which you want to change or replace. This can be done using something like `document.getElementById`, `document.getElementByClassName`, etc. depending on the element that you want to change.

In case you want to fully replace an element, you could apply a similar search for the parent of the element and replace its child with the new element.

After finding an element, you can delete it using `.remove()`. 
You can add the new child with `.appendChild(child)`

[This](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents) is a good source to learn about some basic DOM manipulation.


Hope this helps!
