### ISSUE TITLE
Page Manipulation OFF After Refreshing

### ISSUE THREAD

**Issue by mark100net** [Ruud14/Page-Manipulator#32]
I have the following:

Before clicking Manipulate:

![PageManipulator](https://user-images.githubusercontent.com/1497779/211470609-e0929729-9113-4f5e-be9e-d23add20462b.png)

After clicking Manipulate:

![AfterManipulate](https://user-images.githubusercontent.com/1497779/211471173-5338dc0d-bf90-4470-9070-39d2a9edffaa.png)

When I refresh the page, the "On/Off" indicator is always "Off". I have to click "Manipulate" every time I reload the page for the CSS to take effect.

Is there something set wrong?

Browser is Chrome version 108.0.5359.125 (Official Build) (64-bit).

BTW the "Active Websites:" box can only be expanded vertically. The value there is "https://chess.com/daily-chess-puzzle".

Thanks.

**Comment by Ruud14** [comment]
Hi, 

thanks for reporting this well explained issue.

It seems like you've found a bug that has appeared since the new update.

For now there is an easy fix though: just remove the 'https://' from your url inside "Active Websites:" 
such that it becomes "chess.com/daily-chess-puzzle"

Kind regards,

Ruud

**Comment by mark100net** [comment]
Thanks for your reply.

I had it without the protocol originally. It behaves identically.

**Comment by Ruud14** [comment]
Hmm that is quite strange...

Could you please triple check that it still isn't working?

For me it works perfectly fine with `chess.com/daily-chess-puzzle`.

![image](https://user-images.githubusercontent.com/40769366/211599011-f217b2b4-082e-4de6-b5ad-a4c1495afee0.png)

**Comment by mark100net** [comment]
I already tentuple checked it. It doesn't work. I refresh the page and the element is no longer hidden until I click "Manipulate" again.

I have version 0.5.4. Is that the correct vesion?

**Comment by Ruud14** [comment]
Yes, that is the latest version.

I am still unable to reproduce the issue with `chess.com/daily-chess-puzzle` in active websites.

Could you please check the following:

1. Test if it works with `all` in active websites.
2. Test if manipulating CSS on another page (e.g. google.com) stays after reload. Something simple like 
`body
{
    background-color: blue;
}`
should do.

**Comment by mark100net** [comment]
Well I tried `all` and it worked. Then I put it back to the correct URL and it STILL worked.

Don't ask me to explain that. I don't think I had a typo or else it wouldn't have worked even when I clicked "Manipulate".

I guess it will remain a mystery but now it seems to be working.

Thanks for your responsiveness.
