### ISSUE TITLE
Removal of logo used to work at https://online-go.com but no longer works with upgrade of site

### ISSUE THREAD

**Issue by metaperl** [Ruud14/Page-Manipulator#34]
Hello, I have the following code:

```javascript
try {
	document.getElementsByClassName("ogs-nav-logo")[0].remove();
} catch (error) {
		console.error(error);
}
```

and it used to work fine at https://online-go.com to remove the logo. But they upgraded the site and it no longer works. I do not see any errors in the developer console.

The complete setup for online-go.com is in the attached screenshot.
<img width="561" alt="CZfYxLypOC" src="https://user-images.githubusercontent.com/21293/211588895-4cc989d8-59a2-470b-bd59-285343fe456e.png">

**Comment by metaperl** [comment]
Also: running the same code from the console successfully removes the logo:

<img width="313" alt="chrome_ItBdQ0X1Ci" src="https://user-images.githubusercontent.com/21293/211589351-41460bc4-57c6-4b87-9e04-5f5a59cd0abe.png">

**Comment by Ruud14** [comment]
It seems like there are two elements with class name `ogs-nav-logo` of which the second is the logo. 

`document.getElementsByClassName("ogs-nav-logo")[1].remove();` does the trick :)
