### ISSUE TITLE
How to make sure that every site that ends in "wtc.edu" is changed?

### ISSUE THREAD

**Issue by rajatsrkr** [Ruud14/Page-Manipulator#39]
Trying to make it so that every site that ends in wtc.edu or has that in the name is changed, but not sure how to do that without manually inputting every site in the 'active websites' section (there are over 500 so it's not very efficient to do so)

**Comment by Ruud14** [comment]
There is no built-in functionality to explicitly do this in the extension, the active websites, combined with "matching pages" set to "recursive" only checks the start of URLs.

That does not mean it is not possible though!

You could, even though it is not beautiful, 
1. put "all" in active websites
2. write some javascript to be injected
3. in your javascript, write a check that checks the current URL of the page,
4. if the URL is of the pattern that you want, continue, else, abort. 

Hope this helps :)
