### ISSUE TITLE
Chrome Custom Startup Page Breaks

### ISSUE THREAD

**Issue by Ash-Bird** [Ruud14/Page-Manipulator#40]
The page I set as my Chrome Startup Page had altered html; it's a basic Quote of the Day website. However, once I set it as my start up page, the code hung and I received an error:
![Screenshot 2023-07-27 094123](https://github.com/Ruud14/Page-Manipulator/assets/20172078/5ea14810-baa5-4eef-bf2d-34f6a7a1af0e)

I'm able to edit the page itself, without issue. At startup, is when I have the issues.

**Comment by Ruud14** [comment]
Hi, thanks for reporting!

If I understand correctly:
You have a webpage and you are able to use the extension to change the html. Your changes are also applied again when visiting that website, however the changes are not automatically applied again when having that webpage as your browser startup page. Please correct me if I misunderstood.

I tried reproducing your issue on another website and setting that one as my browser startup page and it seemed to work fine.
Could you provide me the url of the website that you're talking about?
