### ISSUE TITLE
css loading only if i reload page

### ISSUE THREAD

**Issue by JKriszta** [Ruud14/Page-Manipulator#41]
hi,
i made a javascript and a css on a page.
the javascript is loading on page but the css is loading only if i refresh page.
not sure what im doing wrong

**Comment by Ruud14** [comment]
Hi, thanks for reporting!

I was not able to reproduce your issue on other websites. I tried injecting both CSS and JavaScript into google.com simultaneously and it worked fine. The injections were automatically applied again after revisiting the page. 

Could you provide me with the website in question and the code you're injecting?

**Comment by JKriszta** [comment]
hi,

the page is

https://carlyletheassolutions.com/wardrobe/wardrobe.php?owner=85e15d99-c4dc-47d5-a7f6-a96d95277160&ownername=Teqi+Falta&t=83193ee4f2e84851e8bea5f826f562fe5079f5ee

and the scripts i attached as .txt

when css is loaded the text is pink when you hover mouse above it.
i made a gyazo to see how it should look.
https://gyazo.com/e66ff16d6ce1e7930eaf8421a01e21f6

[js.txt](https://github.com/Ruud14/Page-Manipulator/files/12514969/js.txt)
[css.txt](https://github.com/Ruud14/Page-Manipulator/files/12514972/css.txt)

**Comment by Ruud14** [comment]
I tested your code and the CSS and JS both load and work.
I think I don't fully understand what the issue your facing is exactly. For me everything looks exactly like in your video.

**Comment by JKriszta** [comment]
hi, thank you for testing it.
i made new gyazo about it, where i need to refresh page for load css
https://gyazo.com/821b4e7eab0bc41fe5005122a7be30fd
