### ISSUE TITLE
This page can't be manipulated :(

### ISSUE THREAD

**Issue by kaiter999** [Ruud14/Page-Manipulator#43]
This page can't be manipulated :(

edge://extensions/?options=djakfbefalbkkdgnhkkdiihelkjdpbfh

please!

**Comment by Ruud14** [comment]
Special pages like 'about:blank', 'chrome://extensions/', and more (including the page you mentioned) can't be manipulated unfortunately. 

Unfortunately it is simply not possible to modify pages like these.
