### ISSUE TITLE
Where does the extension save the coded file?

### ISSUE THREAD

**Issue by Rehab42** [Ruud14/Page-Manipulator#45]
I know that using the sync it saves a crossed computers but where are the files saved locally before its synced.

**Comment by Ruud14** [comment]
The logic for where something is saved is [here](https://github.com/Ruud14/Page-Manipulator/blob/a61a05cd5e29f8d6fb88b89a2aa3ea41156694ae/popup.js#L441). Before a file is stored using `chrome.storage.sync` it just stays in memory as far as I know. I don't explicitly put files in a specific location before syncing them.
