### ISSUE TITLE
JS not working

### ISSUE THREAD

**Issue by mescwb** [Ruud14/Page-Manipulator#49]
please check this, I tried to remove the element @ 1st row, 1st column to no avail :/
(tried the url with & without 'https://')

![Capturar](https://github.com/user-attachments/assets/5abcf812-0cd7-41ed-a6ca-0b17b94ce3e5)

**Comment by Ruud14** [comment]
I don't have access to that specific url, however from your screenshot it seems to be a page that shows search results. Usually, when performing a search, the results will not load immediately, instead some loading animation will show and then the results will show up. This means that, right after opening the page, the element that you are searching for with `document.querySelector` probably is not loaded in yet. Hence, when your javascript is run, it finds no elements with that query selector.

To solve this, please try adding a delay before running your code. You could use `setTimeout` for this for example.

**Comment by mescwb** [comment]
hi again just before your response I had remove it from Edge and now I've added it again but it does not work anymore in *any* page :/ hence I cannot try your suggestion

![Capturar 2](https://github.com/user-attachments/assets/f2439753-c655-4689-bf73-0e8d973b15cb)
![Capturar](https://github.com/user-attachments/assets/0dcfd68c-97f9-439a-a6d7-5ce40f48ee32)

**Comment by Ruud14** [comment]
Please restart chrome completely, afterwards it should work.
