### ISSUE TITLE
This page can't be manipulated :(

### ISSUE THREAD

**Issue by poldis** [Ruud14/Page-Manipulator#7]
Every page i try the extension on "can't be manipulated". No matter which page (amazon, pinterest etc.). Removing and adding it again changed nothing. Please help me with this since I'd really like to use this extension.

**Comment by Ruud14** [comment]
First try to restart your browser (if you haven't already).
If you are using Google Chrome as your browser you should make sure that the extension has permission to access the page.
You can check if the extension has access to the page by doing the following:
1. Go to [the Google Chrome extensions page](chrome://extensions) (chrome://extensions)
2. Look for the 'Page Manipulator' extension and click on the 'details' button.
3. Here there should be an option to give the extension access to 'all sites'. Choose this option and restart the browser.

Please let me know if this works.
Please give me some info about your operating system, browser and browser version if it doesn't.
