### ISSUE TITLE
External HTTP requests 

### ISSUE THREAD

**Issue by biller-aivy** [Ruud14/Page-Manipulator#8]
Could you add an example for an http request to get some data and add it to a page? 

Would be nice!

**Comment by biller-aivy** [comment]
Maybe an example with an Button in Page to get the data.

inject an Button, if someone clicks the button, some data is injected from external API

**Comment by Ruud14** [comment]
```
let btn = document.createElement("button");
btn.innerHTML = "<h1>Click Me</h1>";
btn.onclick = function() {
    fetch("http://worldtimeapi.org/api/timezone/Europe/Amsterdam")
    .then(response => 
    response.json().then(data => ({
        data: data,
        status: response.status
    })
    ).then(res => {
        let div = document.createElement("div");
        div.innerHTML = "<h1>"+res.data.datetime+"</h1>";
        document.body.prepend(div);
        console.log(res.data)
    }));
    
};
document.body.prepend(btn);
```

This code adds a button to the top of the page and when this button is clicked it will make an http request to an external time api. After a few seconds the response from the api will be added to the top of the page.
Note that this only works on HTTP sites and not on HTTPS ones.

Hope this helps :)
