### ISSUE TITLE
Could you create a simple example for React

### ISSUE THREAD

**Issue by davidbiller** [Ruud14/Page-Manipulator#9]
I would like to push React components into the HTML. 
Surely this is possible or? If necessary then also first translated with Babel.

**Comment by Ruud14** [comment]
I've never used react before but I think that I managed to do what you wanted.

create a new javascript file inside Page Manipulator with the following contents:

```javascript
'use strict'

const container = document.createElement("div");
container.id = "like_button_container";
document.body.appendChild(container);

const react1 = document.createElement("script");
react1.type = "text/javascript";
react1.src = "https://unpkg.com/react@16/umd/react.development.js";
document.head.appendChild(react1);

const react2 = document.createElement("script");
react2.type = "text/javascript";
react2.src = "https://unpkg.com/react-dom@16/umd/react-dom.development.js";
document.head.appendChild(react2);


var newScript = document.createElement("script");
newScript.type = "module";
var inlineScript = document.createTextNode(
`

const e = React.createElement;

class LikeButton extends React.Component {
  constructor(props) {
    super(props);
    this.state = { liked: false };
  }

  render() {
    if (this.state.liked) {
      return 'You liked this.';
    }

    return e(
      'button',
      { onClick: () => this.setState({ liked: true }) },
      'Like'
    );
  }
}

const domContainer = document.querySelector('#like_button_container');
ReactDOM.render(e(LikeButton), domContainer);

`
);

newScript.appendChild(inlineScript);
setTimeout(() => {document.body.appendChild(newScript);}, 2000);

```

Since it takes time for react to load after adding `react1` and `react2` to the page,
we wait 2 seconds before adding the actual react code to the page.

This is might be a bit of a hacky solution but I couldn't quickly come up with anything else.
Maybe someone familiar with react could come up with a better solution.

Anyway, 
Hope this helps :)

**Comment by davidbiller** [comment]
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'report-sample' 'sha256-6gLjSWp3GRKZCUFvRX5aGHtECD1wVRgJOJp7r0ZQjV0=' 'unsafe-inline' s.c.lnkd.licdn.com static-fstl.licdn.com static-src.linkedin.com


Maybe I have to get the HTML from Backend.

**Comment by Ruud14** [comment]
Did you get that error while executing the example that I gave you or with a modified version of that?
In case of a modified version, please first verify that the example I gave you works. If the example works then the problem will most likely be in the code you modified.

**Comment by biller-aivy** [comment]
With your example Code, just tried ist on LinkedIn.

**Comment by Ruud14** [comment]
Ah Okay,
It seems to have something to do with LinkedIn.
People here: https://stackoverflow.com/questions/17653384/refused-to-execute-inline-script-because-it-violates-the-following-content-secur
are also having the same issue.
Try the most upvoted solution.
